//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPROC_RanchoNuevo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class actualizacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public actualizacion()
        {
            this.fila = new HashSet<fila>();
            this.usuario = new HashSet<usuario>();
        }
    
        public int idActualizacion { get; set; }
        public Nullable<double> temperatura { get; set; }
        public Nullable<int> nVolteos { get; set; }
        public string Observaciones { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fila> fila { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
