//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAPROC_RanchoNuevo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fila
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fila()
        {
            this.actualizacion = new HashSet<actualizacion>();
            this.lote = new HashSet<lote>();
        }
    
        public int idFila { get; set; }
        public string identificadorFila { get; set; }
        public Nullable<int> nViajes { get; set; }
        public Nullable<double> cCascarrillo { get; set; }
        public string Comentarios { get; set; }
        public Nullable<double> toneladasLinea { get; set; }
        public Nullable<double> Produccion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<actualizacion> actualizacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lote> lote { get; set; }
    }
}
